include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

    # Disable the lint rule for non-constant identifier names.
    non_constant_identifier_names: false

    # Disable the lint rules for preferring const constructors and literals.
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

    # Disable the lint rule for preferring conditional assignments.
    prefer_conditional_assignment: false

    # Disable the lint rule for constant identifier names.
    constant_identifier_names: false

analyzer:
  exclude:
    # Exclude generated files to prevent unnecessary warnings and errors.
    - '**/*.g.dart'
    - '**/*.freezed.dart'

  errors:
    # Ignore errors related to invalid annotation targets.
    invalid_annotation_target: ignore





