name: neighborly_flutter_app
description: "A new Flutter project."
publish_to: "none" 

# Version of the app
# on every new release you have to updtae the version
version: 1.0.0+2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  internet_connection_checker: ^1.0.0+1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  intl: 0.19.0
  geolocator: ^8.0.0
  video_player: ^2.8.7
  image_picker: ^1.1.2
  mime: ^1.0.5
  toggle_switch: ^2.3.0
  geocoding: ^3.0.0
  hive:
  hive_flutter: ^1.1.0 
  share_it: ^0.7.0
  permission_handler: ^10.4.2             
  
  # Notification 
  firebase_core: ^3.4.0
  flutter_local_notifications: ^17.2.2 
  firebase_messaging: ^15.0.4

  # Socket
  socket_io_client: ^2.0.3+1
  
  # UI
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  line_icons: ^2.0.3
  readmore: ^3.0.0
  timeago: ^3.7.0
  scrollable_clean_calendar: ^1.5.0
  mobkit_dashed_border: ^0.0.6
  badges: ^3.1.2

  # Form
  dropdown_button2: ^2.3.9
  remove_diacritic: ^0.9.0
  flutter_xlider: ^3.5.0
  flutter_typeahead: ^5.2.0 
  flutter_image_compress: ^2.3.0
  cross_file: ^0.3.4+2
  bloc: ^8.1.4
  image_cropper: ^8.0.2
  # uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
